import { Metadata } from "next";

export const metadata: Metadata = {
  title: "XO | leaderboard",
  description: "Generated by create next app",
};

export default function LeaderboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
        {children}
    </main>
  );
}
