import { Metadata } from "next";

export const metadata: Metadata = {
  title: "XO | play",
  description: "Generated by create next app",
};

export default function PlayLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="w-full h-full ">
        {children}
    </main>
  );
}
