import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { ClerkProvider } from "@clerk/nextjs";
import ConvexClientProvider from "@/providers/ConvexClientProvider";
import { Boxes } from "@/components/ui/background-boxes";
import Navbar from "./_components/navbar";
import Footer from "./_components/footer";
import FadeInWhenVisible from "@/components/animation/FadeInWhenVisible";
import { Toaster } from "@/components/ui/sonner";
import { Spotlight } from "@/components/ui/spotlight";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "XO | home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} w-full antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <ClerkProvider>
            <ConvexClientProvider>
              <div className="bg-background text-foreground flex min-h-[100dvh] flex-col items-center justify-items-center">
                <Navbar />
                <main className="flex-1 min-h-[100vh] w-full">
                  <Spotlight
                    className="bg-primary blur-2xl"
                    size={64}
                    springOptions={{
                      bounce: 0.3,
                      duration: 0.1,
                    }}
                  />
                  {children}
                </main>
                <Footer />
              </div>
              <Toaster richColors />
            </ConvexClientProvider>
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
